In [ ]:
# Numpy_김기중_2023183273

In [5]:
import numpy as np

In [10]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [8]:
a2 = a[np.newaxis, :]

In [14]:
a2.shape

(1, 6)

In [17]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [22]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print(a[0])

[1 2 3 4]


In [27]:
import numpy as np
a = np.array([1,2,3])

In [28]:
np.zeros(2)

array([0., 0.])

In [29]:
np.ones(2)

array([1., 1.])

In [38]:
np.empty(2)

array([1., 1.])

In [40]:
np.arange(4)

array([0, 1, 2, 3])

In [43]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [44]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [48]:
arr = np.array([2,1,5,3,7,4,6,8])

In [49]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [51]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [53]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])

In [55]:
array_example.ndim

3

In [56]:
array_example.size

24

In [57]:
array_example.shape

(3, 2, 4)

In [58]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [59]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [61]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [62]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [63]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [64]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [65]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [66]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [67]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [68]:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

In [69]:
data = np.array([1,2,3])

In [70]:
data[1]

2

In [71]:
data[0:2]

array([1, 2])

In [72]:
data[1:]

array([2, 3])

In [73]:
data[-2:]

array([2, 3])

In [75]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [76]:
print(a[a<5])

[1 2 3 4]


In [78]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [79]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [80]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [81]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [82]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [83]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [84]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [85]:
print(a[b])

[1 2 3 4]


In [86]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [87]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [88]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [89]:
a1 = np.array([[1,1],[2,2]])

In [90]:
a2 = np.array(([3,3],[4,4]))

In [91]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [92]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [93]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [94]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [96]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [97]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [98]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [99]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [100]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
b2 = a.copy()

In [111]:
b2[0][0] = 98
b2

array([[98,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
data = np.array([1,2])

In [113]:
ones = np.ones(2, dtype=int)

In [114]:
data + ones

array([2, 3])

In [115]:
data - ones

array([0, 1])

In [116]:
data * data

array([1, 4])

In [117]:
data / data

array([1., 1.])

In [118]:
a = np.array([1,2,3,4])
a.sum()

10

In [120]:
b = np.array([[1,1],[2,2]])

In [121]:
b.sum(axis=0)

array([3, 3])

In [122]:
b.sum(axis=1)

array([2, 4])

In [123]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [124]:
data.max()

2.0

In [125]:
data.min()

1.0

In [126]:
data.sum()

3.0

In [127]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [128]:
a.sum()

4.8595784

In [129]:
a.min()

0.05093587

In [130]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [131]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
data[0,1]

2

In [134]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [135]:
data[0:2, 0]

array([1, 3])

In [136]:
data.max()

6

In [137]:
data.min()

1

In [138]:
data.sum()

21

In [139]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [140]:
data.max(axis=0)

array([5, 6])

In [141]:
data.max(axis=1)

array([2, 5, 6])

In [142]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [143]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [144]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [145]:
np.ones(3)

array([1., 1., 1.])

In [146]:
np.zeros(3)

array([0., 0., 0.])

In [148]:
rng = np.random.default_rng()
rng.random(3)

array([0.95942536, 0.23122163, 0.07711992])

In [149]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [150]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [151]:
rng.random((3, 2)) 

array([[0.80123195, 0.75749072],
       [0.08666421, 0.66266406],
       [0.67028023, 0.69578161]])

In [152]:
rng.integers(5, size=(2, 4)) 

array([[2, 1, 4, 1],
       [1, 3, 0, 3]])

In [153]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [154]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [155]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [156]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [157]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [158]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [159]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [160]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [161]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [162]:
print(indices)

[0 1 2]


In [163]:
print(occurrence_count)

[2 1 1]


In [164]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [165]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [167]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [169]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [170]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [171]:
reversed_arr = np.flip(arr)

In [172]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [173]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [174]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [175]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [176]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [177]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [178]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [179]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [180]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [181]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [182]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [183]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [184]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
